name: charts_common
version: 0.12.0
description: A common library for charting packages.
homepage: https://github.com/google/charts

#  @kris changed sdk: '>=2.12.0 <3.0.0' and removed versions of all dependencies - to get latest
# flutter test -  all tests  passed

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: 
  intl: 
  logging: 
  meta: 
  vector_math: 

dev_dependencies:
  mockito: 
  test: 
