name: charts_flutter
version: 0.12.2
description: Material Design charting library for flutter.
homepage: https://github.com/google/charts

#  @kris changed sdk: '>=2.12.0 <3.0.0' and removed versions of all dependencies - to get latest
# flutter test -  all tests  passed
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: 
#@kris  added this to get over the charts_common local path
#pubblishable packages can't have local path 
publish_to: none
dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of charts_flutter will point to the pub version of charts_common.
  # The latest pub version is commented out and shown below as an example.
  #charts_common: ^0.12.0
  #path: ../charts_common/
  charts_common:  #google charts - officially discontinued
    git:
      url: https://github.com/clinsign/google-flutter-charts.git
      ref: master
      path: charts_common
      
  collection: 
  flutter:
    sdk: flutter
  intl: 
  logging: 
  meta: 


dev_dependencies:
  mockito: 
  build_runner: 
  flutter_test:
    sdk: flutter
  test: 
